### ISSUE TITLE
JSON Load Error (I have successfully checked with Json Formatter)

### ISSUE THREAD

**Issue by rahaaatul** [Nixeld/MudaeAutoBot#3]
I know you're gonna ask me to read the README but I've already did that. This is the error: with also the default one you provided:

```python
Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\Compressed\MudaeAutoBot-main\MudaeAutoBot.py", line 33, in <module>
    settings = json.load(jsonf)
               ^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python\3.12\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python\3.12\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python\3.12\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python\3.12\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 4 column 7 (char 114)
```

This is a valid JSON:
![image](https://github.com/Nixeld/MudaeAutoBot/assets/86149861/932177f9-1938-488f-bc40-30c931b42b97)

```json
{
   "token":"mYtoKen",
   "channel_ids":[
      "<channel_ids>"
   ],
   "slash_ids":[
      "<channel_ids>"
   ],
   "slash_guild_ids":[
      "<guild_ids>"
   ],
   "claim_delay":3,
   "kak_delay":3,
   "use_emoji":"<:keqing_love:795077041761288214>",
   "roll_this":"wa",
   "slash_this":"wa",
   "rolling":"True",
   "slash_rolling":"True",
   "daily_claiming":"True",
   "poke_rolling":"True",
   "series_list":[
      "Honkai Impact 3rd"
   ],
   "namelist":[
      "Zero Two",
      "Rem",
      "Megumin"
   ],
   "emoji_list":[
      "kakera",
      "kakeraP",
      "kakeraT",
      "kakeraG",
      "kakeraY",
      "kakeraO",
      "kakeraR",
      "kakeraW",
      "kakeraL"
   ],
   "soulemoji_list":[
      "kakeraO",
      "kakeraR",
      "KakeraW",
      "KakeraL"
   ],
   "min_kak":500,
   "last_true":"True",
   "last_claim_min":61,
   "min_kak_last_min":10
}
```

**Comment by HANSSS9631** [comment]
I am pretty sure that channel_ids, slash_ids and slash_guild_ids can be a string or a number so both is correct.

**Comment by Nixeld** [comment]
Did you fill in these 3 fields?
`channelids` - Which channels to Roll and monitor e.g. 807##########948 (Channel ID)
`slash_ids` - Which channels to Slash roll e.g. 807##########948 (Channel ID)
`slash_guild_ids` - Which Guild to Slash roll e.g. 807##########948 (Server ID)

The slash_ids and slash_guild_ids lists are interconnected. The order of the IDs in both lists is important. Each `slash_id` corresponds to a `slash_guild_id` at the same position in their respective lists.

For instance, the first `slash_id` in the list should be associated with the server identified by the first `slash_guild_id`. Similarly, the second `slash_id` corresponds to the server identified by the second `slash_guild_id`, and so on.

It should look something like this.
```
   "channel_ids":[
      1063456558643695656,
      1017222443338825818
   ],
   "slash_ids":[
      1063456558643695656,
      1017222443338825818
   ],
   "slash_guild_ids":[
      894925535870865498,
      894925535870865498
   ],
   ```

**Comment by HANSSS9631** [comment]
If there is still an issue, reopen
